### ISSUE TITLE
How to fix a package version number tag?

### ISSUE THREAD

**Issue by acesnik** [conda-forge/conda-forge-repodata-patches-feedstock#150]
There was a typo in an early release of a package, `dotnet-runtime`, where it was listed as `3.1.19` instead of `3.1.9` (https://github.com/conda-forge/dotnet-feedstock/issues/26). Now, anytime someone requests `dotnet-runtime=3`, they get this older one because a newer version than 3.1.19 doesn't exist. Is this the right place to change this version tag? 

How would I do that? I see numerous examples in `gen_patch_json.py` and in the merged pull requests for changing dependency pins, for example, but I don't see how to change an already listed package version, so I'm not sure how to proceed.

This is the link that led me here in the first place: https://conda-forge.org/docs/orga/guidelines.html#fixing-broken-packages.

---

- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

**Comment by xhochy** [comment]
I think you are looking for something similar to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py#L558-L562

Here we replace the `run` dependency `"pyarrow >=0.13.0,!=0.14.0,<2"` with the new  dependency `"pyarrow >=0.17.1,<2"` for the `kartothek` package. This sounds like the thing you are trying to do.

**Comment by isuruf** [comment]
Since the version is wrong, you need to mark it as broken. See https://github.com/conda-forge/admin-requests

**Comment by acesnik** [comment]
Okay, done! https://github.com/conda-forge/admin-requests/pull/273
Thanks for the help.
