### ISSUE TITLE
patch old versions of nbconvert to force mistune < 2

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-repodata-patches-feedstock#198]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

See here: https://github.com/conda-forge/nbconvert-feedstock/pull/54

**Comment by bollwyvl** [comment]
Related:
- https://github.com/conda-forge/admin-requests/pull/358
- https://github.com/conda-forge/mistune-feedstock/pull/23

Not sure if we now need to go back and patch hundreds of nbconverts...

**Comment by beckermr** [comment]
I think we can close this.
