### ISSUE TITLE
Testing of repodata patches

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-repodata-patches-feedstock#29]
It would be useful to have some testing of repodata patches. Not sure how this would work in practice. However this would be useful to catch errors before they ship. Also it would be useful to aid new contributors as they gain confidence in making changes here.

**Comment by isuruf** [comment]
It is tested. I think the issue may have been that the status didn't get through.

**Comment by jakirkham** [comment]
Ah great! Sorry if I'm just clueless then 🙂

How is this being tested?

**Comment by isuruf** [comment]
Unit tests at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/test_gen_patch_json.py
No integration tests.
