### ISSUE TITLE
rebuild once a week or so?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-repodata-patches-feedstock#41]
Due to great work by @isuruf, we now compute the license_family field for packages here as part of the repodata patching process. As packages are updated/added on the index, we will thus need to rebuild the repodata patches to make sure the license_family fields are synced and filled out. 

My proposal is that we have a cron job make a PR to rebuild this feedstock once a week and we merge that PR with an automerge label.

**Comment by jakirkham** [comment]
I thought this got run as part of the CDN mirroring process. Is that not right?

**Comment by isuruf** [comment]
What do you mean by `this got run`?

**Comment by jakirkham** [comment]
This is the script that patches the repodata right?

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/master/recipe/gen_patch_json.py

**Comment by beckermr** [comment]
That gets run when the package is built. The data from the built package is then consumed. If we don’t rebuild, anaconda doesn’t get updates

**Comment by jakirkham** [comment]
Thanks for the clarification. TBH I've never really got a handle on how this works, but also haven't spent that much time with it 🤷‍♂️

**Comment by beckermr** [comment]
closed by https://github.com/conda-forge/admin-requests/pull/345
