### ISSUE TITLE
Lack of useful documentation for testing conda-forge-repodata-patches-feedstock

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/conda-forge-repodata-patches-feedstock#493]
### Comment:

The documentation for contributing a patch to the conda-forge-repodata-patches-feedstock is severely lacking. In its entirety it appears to be:

> If the only issue is in the package metadata, we can directly patch it using the [repo data patches feedstock](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock). To change the repo data for your package, make a PR on the feedstock. &mdash; https://conda-forge.org/docs/orga/guidelines.html

In PR https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/492 I found that what appears to be sufficient to run the checklist is an environment with

```
micromamba create --yes --name debug --channel conda-forge python tqdm requests packaging license-expression conda-build
```

but why did I need to spend 5 minutes on a bad internet connection finding this out? It would be better to include some useful information in the README and an `environment.yml` that you can use to create the minimal environment to run `recipe/show_diff.py`?

This seems like documentation that should exist _in_ this repository and not necessarily elsewhere, as you need to fork and clone the feedstock to make a patch and run `show_diff.py`.

**Comment by ocefpaf** [comment]
Conda-forge is maintained by volunteers on their spare time. Most of docs need work, if you can send a PR ir would be .oat welcomed!

**Comment by matthewfeickert** [comment]
Thanks for the recommendation @ocefpaf. :+1: I'll throw it on the heap and maybe get to it in coming weeks, though I would welcome someone else to beat me to it.

**Comment by jakirkham** [comment]
Thanks for sharing your experience. Sorry to hear it was rather rough ❤️‍🩹

Yeah agree this is probably the hardest and least documented part of our infrastructure 😞

It's also been tricky to add good docs here as the folks who know the most have significant demands on their time. So improving docs ends up low on their task list

Conversely those with time and interest (and perhaps even funding) to work on docs do not necessarily know the infrastructure well enough to explain it to others

All this to say I agree with the criticism and it is valid. We have just ended up with the current documentation as a result of these constraints (it shouldn't be this way though)

There is some info in [this Q&A]( https://conda-forge.org/docs/user/faq.html#faq-abi-incompatibility ), but it could benefit from being expanded upon (and maybe moving to a proper section in the docs)

In terms of the script, agree we could do a better job documenting what is needed

If there are particular areas where you think this info makes sense to add, please give it a go. We can then iterate on it

**Comment by beckermr** [comment]
We do run the diff in ci but the permissions model is too complex for it to post the diff on the pr.

**Comment by beckermr** [comment]
We also need to completely overhaul this code. It is far too complex and too many patches are defined in the code. Most patches should be expressive as static yaml which turn into the relevant modifications.

**Comment by jakirkham** [comment]
Agree simplification of the patching process is needed/welcome :)

**Comment by jdblischak** [comment]
Wow, I didn't realize the patch system had been completely converted to a YAML template system. This looks much improved. Thanks to all who worked on it!

For anyone else that finds themselves here, the documentation for creating a patch is at `recipe/README.md`:

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/README.md

(for anyone new to conda-forge, this README unfortunately can't be at the top-level because the top-level README in all conda-forge feedstocks is automatically rendered by a bot)

**Comment by jdblischak** [comment]
> We do run the diff in ci

@beckermr Where is `show_diff.py` being run in CI? I checked the Azure log and `recipe/meta.yaml`, but I couldn't find where it was being invoked

> but the permissions model is too complex for it to post the diff on the pr.

What about creating a GitHub Actions workflow that runs `show_diff.py` and posts the results to the PR? I'd be willing to help with this if that is something that would be approved/merged by the core team

**Comment by beckermr** [comment]
Show diff is run in the conda-build testing steps. See this [job](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=852404&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3) around line 330 or so for example.

For GHA, if you can work it out that the GHA work flow can run for PRs only without enhanced permissions beyond a token available on PRs, then it might be possible. However, the tokens github provides to PRs from forks are read-only: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token. 

It is too much of a security risk to run `show_diff.py` using GHA's ability to run code from a PR on the upstream repo using the, e.g., `issue_comment` or `pull_request_target` events with code to checkout the forked code. Repodata patches can have arbitrary code in them and so need to be reviewed before they can be run in enhanced security environments.

**Comment by jdblischak** [comment]
@beckermr Thanks for the explanations!

> Show diff is run in the conda-build testing steps.

Now I understand. I was looking for the script `show_diff.py` to be invoked. But I see it is simply recreating the default conda-build behavior to patch the repodata using  `conda_build.index._apply_instructions()`

> It is too much of a security risk to run `show_diff.py` using GHA's ability to run code from a PR on the upstream repo

Yeah, you're right. It wouldn't be secure to elevate the token for a PR from a fork (and as you noted, GitHub purposefully prevents this possibility). I had thought the permissions complexity you were referring to was authenticating the Azure build to be able to post to the GitHub PR, ie authentication between Azure and GitHub

**Comment by jdblischak** [comment]
I've done my best to address this Issue in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/675. Feedback welcome!
