### ISSUE TITLE
How do I generate a diff from a YAML patch?

### ISSUE THREAD

**Issue by maresb** [conda-forge/conda-forge-repodata-patches-feedstock#557]
### Comment:

I'm working on #556 and I've spent way too much time unsuccessfully running `show_diff.py` to view the resulting diff. After taking a look at the source code, I don't see any YAML patch stuff in `show_diff.py`.

I'm not sure that my YAML patch is correct, because I need my upper bound to be `<1.26` rather than `<=1.26`, and without being able to see a diff, I don't know what the actual behavior is.

Any help would be greatly appreciated.

EDIT: I see that YAML stuff is transitively imported from `gen_patch_json.py`, but that still doesn't explain why my diff is empty.

**Comment by beckermr** [comment]
If the diff is empty that means the patch didn't apply to anything. The show_diff.py script does everything.

**Comment by beckermr** [comment]
I am closing this since the associated PR is merged.
