### ISSUE TITLE
No more `.github/PULL_REQUEST_TEMPLATE.md`

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-repodata-patches-feedstock#708]
It seems that https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/commit/9870760c24d98d4108fe53721ab54d7cb6b98617 deleted it. Do we need an exception somewhere in smithy?

CC @beckermr

**Comment by h-vetinari** [comment]
Let's reopen to figure out how deleting the template can be avoided going forward; might need work in smithy

**Comment by beckermr** [comment]
Maybe this?

https://conda-forge.org/docs/maintainer/conda_forge_yml/#skip-render
