### ISSUE TITLE
ENH: support removal of upper bounds in yaml patching

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-repodata-patches-feedstock#880]
I'm in a situation (#879) where I need to loosen a dependency from a run-export, but not just replace the upper bound, but remove it completely. In reference to the API of `pin_subpackage`, I had written this as:
```yaml
  - loosen_depends:
      name: libre2-11
      upper_bound: None
```
however, that doesn't work as intended. `None` gets interpreted as a string and so we get
```diff
linux-64::libarrow-13.0.0-h5534346_26_cpu.conda
-    "libre2-11 >=2023.6.2,<2024.0a0",
+    "libre2-11 >=2023.6.2,<None.0a0",
```

I'm not sure what the best way to implement this would be. Using `"None"` as a value seems fragile, because the [processing](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/acf889cd2228b6e260b14b67b8378c0c0be62345/recipe/patch_yaml_utils.py#L528-L545) for `"loosen_depends"` is full of `None` handling already. Perhaps we could a magic cookie like `"upper_bound: |remove|"`?

This approach would be following the current requirement of "you must give one of max_pin or upper_bound " outlined in the readme for [`loosen_depends`](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/acf889cd2228b6e260b14b67b8378c0c0be62345/recipe/README.md?plain=1#L149-L157). A more invasive alternative would be to introduce a third option next to `max_pin` and `upper_bound`, e.g. `remove:` which can be either `"upper"` or `"lower"` (though I note that `{tighten,loosen}_depends` don't really support handling of lower bounds anyway).

CC @beckermr

**Comment by h-vetinari** [comment]
Thoughts on this @beckermr?

**Comment by beckermr** [comment]
Using an a branch on `None` will be fine as long as we branch right at the top instead of trying to do it throughout the function. Should be a straight-forward PR and the tests should be easy enough to write to catch all of the edge cases. PRs welcome!

**Comment by h-vetinari** [comment]
> Using an a branch on `None` will be fine

But it won't be `None`, it'll be `"None"`, because yaml can only produce strings/ints/floats, not `None`. And that distinction is IMO way too easy to confuse, so rather than `"None"`, I think we should take a more recognizably magic cookie like `"|remove|"` or `"<remove>"`.

**Comment by beckermr** [comment]
The value null will produce none. The actual cases are not that hard to enumerate and are easier than making people remember a special value they have no seen before.

**Comment by h-vetinari** [comment]
so IIUC you propose that people write the following in the yamls:
```yaml
  - loosen_depends:
      name: libre2-11
      upper_bound: null  # but not None
```

> easier than making people remember a special value they have not seen before.

To my mind, `null` fall exactly under that category as well, but 🤷

**Comment by h-vetinari** [comment]
I added something in #879. It seems to work, but I'm not sure what you had in mind, esp. w.r.t. testing.

**Comment by beckermr** [comment]
We can support either null or text None. It is a simple or statement. No need to force folks into one or the other.

**Comment by beckermr** [comment]
Also null is not random. Yaml is a superset of json and "null" is part of the json standard. See here https://www.json.org/json-en.html

**Comment by beckermr** [comment]
Ok. I'll back out my commit then. I don't actually care here but I dont want a value that we have co
Platelet made up.

**Comment by h-vetinari** [comment]
I don't feel super strongly about supporting `"None"` or not - it was the thing I reached for first after all - so I left your commit in but removed the mixed-case variants.
