### ISSUE TITLE
Add summary of how patch application actually happens to recipe/README

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/conda-forge-repodata-patches-feedstock#905]
The existing [`recipe/README`](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/70a9691c16c34d5299aeb42b54ed00e35f32c50a/recipe/README.md) does a pretty good job of explaining how to make a patch, but after that there's no description of what happens _after_ your patch PR has been merged. There's also no documentation on what happens post PR on https://conda-forge.org/docs/maintainer/ (e.g. https://conda-forge.org/docs/maintainer/infrastructure/#conda-forge-repodata-patches). I assume that the answer is, that like most things on conda-forge, some great automation comes along, picks up the patches generating information, and goes and applies them to the metadata associated with the actual distribution on https://anaconda.org/conda-forge/ (?). However, it would be useful to have documented:

* What is actually happening
* When it happens
* How to track what is happening so that you know when to try to rerender or install from a feedstock again.

I understand that for most maintainers the answer of "try again every 24 hours until things work" is a perfectly practical and good answer, though I think it would be useful to make things a bit more explicitly documented.

**Comment by beckermr** [comment]
Right. The issue here is that we don't actually know. Anaconda, Inc manages all of the infrastructure that applies the patches and that infrastructure is tied into the CDN update process. FWIW, patches should be live within an hour or so in most cases these days.

**Comment by matthewfeickert** [comment]
> Right. The issue here is that we don't actually know. Anaconda, Inc manages all of the infrastructure that applies the patches and that infrastructure is tied into the CDN update process. FWIW, patches should be live within an hour or so in most cases these days.

Ah that's both surprising, but also helpful (in my mind) to understand. Thanks very much @beckermr!

Would you be open to me making a small PR to note these details?

**Comment by beckermr** [comment]
sure feel free!
